// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa3R8qNkCqWqWg3-2DV873xu-SCz9ITIU',
    appId: '1:1000745687969:web:3a54ecdffff9cf07bc09e0',
    messagingSenderId: '1000745687969',
    projectId: 'mentallica-ab479',
    authDomain: 'mentallica-ab479.firebaseapp.com',
    storageBucket: 'mentallica-ab479.appspot.com',
    measurementId: 'G-2W2KQPYPW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5piMhZZ6BhdLfc5Miy5_xNXxhcyQNYsE',
    appId: '1:1000745687969:android:159004a860194ac0bc09e0',
    messagingSenderId: '1000745687969',
    projectId: 'mentallica-ab479',
    storageBucket: 'mentallica-ab479.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiCzBB1b0Gg4mUL0BGsCvmd5vkhUh01xQ',
    appId: '1:1000745687969:ios:26cf14ee68f34b41bc09e0',
    messagingSenderId: '1000745687969',
    projectId: 'mentallica-ab479',
    storageBucket: 'mentallica-ab479.appspot.com',
    iosBundleId: 'com.example.mentallica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiCzBB1b0Gg4mUL0BGsCvmd5vkhUh01xQ',
    appId: '1:1000745687969:ios:467e1cc23befe1debc09e0',
    messagingSenderId: '1000745687969',
    projectId: 'mentallica-ab479',
    storageBucket: 'mentallica-ab479.appspot.com',
    iosBundleId: 'com.example.mentallica.RunnerTests',
  );
}
